name: Sophisticated Mexican
favicon: null
layout_spectrum: 0.34525651833973825
typography_spectrum: 0.8884227885864675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.17191702430136502
  lightness: 0.7009105642791837
  saturation: 0.2241166785825044
  rhythmicContrast: 0.8210361318197101
purpose: []
